### ISSUE TITLE
Deprecation warning on global package

### ISSUE THREAD

**Issue by Its-Alex** [spm-style/cli#2]
Unhandled error when install global package

```shell
spm i test -r
(node:8001) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

**Comment by ScandalousMan** [comment]
Hello Alex,

commit 4306b4531ea7162472e0503560358a2c07f265a7
Merge: 753117e 679a0be
Author: spm-style <adrien@start-to-up.com>
Date:   Tue Dec 19 16:19:33 2017 +0100

While updating the current path install logic (refer to PR #4 ) we took the opportunity to move spm registry from the previous protected path to the .spm/registry folder located in HOME

Have a good day !

Adrien
